// International Travel Packages with exact INR pricing
// These are the premium international destinations with special pricing

export type InternationalPackage = {
  id: string;
  destination: string;
  countryCode: string;
  duration: string;
  nights: number;
  days: number;
  priceINR: number;
  pricePerPerson: boolean;
  taxes: string;
  flightIncluded: boolean;
  highlights: string[];
  inclusions: string[];
  image: string;
  description: string;
};

export const INTERNATIONAL_PACKAGES: InternationalPackage[] = [
  {
    id: "thailand-3n-4d",
    destination: "Thailand",
    countryCode: "THA",
    duration: "3N / 4D",
    nights: 3,
    days: 4,
    priceINR: 19999,
    pricePerPerson: false,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Bangkok Temples",
      "Pattaya Floating Market",
      "Coral Island Speedboat Tour",
      "Safari World",
    ],
    inclusions: [
      "Premium Hotel Stay",
      "Daily Buffet Breakfast",
      "Private Airport Transfers",
      "Curated Sightseeing Tours",
    ],
    image: "thailand bangkok wat arun",
    description:
      "Discover the enchanting Land of Smiles - From the golden spires of Bangkok to the turquoise waters of Pattaya's pristine islands.",
  },
  {
    id: "singapore-malaysia-5n-6d",
    destination: "Singapore & Malaysia",
    countryCode: "SGP",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 70000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Gardens by the Bay",
      "Universal Studios",
      "Genting Highlands",
      "Batu Caves",
      "Petronas Twin Towers",
    ],
    inclusions: [
      "Luxury 4-Star Accommodation",
      "Inter-city Transfers",
      "Daily Breakfast",
      "Sightseeing with Expert Guides",
    ],
    image: "singapore gardens by the bay night",
    description:
      "A perfect blend of futuristic innovation and cultural heritage - Experience the high-tech wonders of Singapore and the vibrant charm of Malaysia.",
  },
  {
    id: "singapore-malaysia-cruise-7n-8d",
    destination: "Singapore & Malaysia",
    countryCode: "SGP",
    duration: "7N / 8D",
    nights: 7,
    days: 8,
    priceINR: 117000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Luxury Cruise Experience",
      "Sentosa Island Island",
      "Kuala Lumpur City Tour",
      "Genting Highlands",
      "Marina Bay Sands",
    ],
    inclusions: [
      "Premium Cruise Cabin",
      "5-Star Hotels",
      "All Meals on Cruise",
      "Premium Sightseeing",
      "VIP Transfers",
    ],
    image: "cruise ship singapore",
    description:
      "The ultimate luxury voyage - Sail across the Malacca Strait on a premium cruise and explore the most iconic landmarks of Singapore and Malaysia.",
  },
  {
    id: "azerbaijan-5n-6d",
    destination: "Azerbaijan (Baku)",
    countryCode: "AZE",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 99999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Flame Towers Night View",
      "Gobustan Mud Volcanoes",
      "Baku Old City (Icherisheher)",
      "Heydar Aliyev Center",
    ],
    inclusions: [
      "Boutique Hotel Stay",
      "Gourmet Breakfast",
      "Private 4x4 Tour to Gobustan",
      "English Speaking Guide",
      "Airport Transfers",
    ],
    image: "baku flame towers night",
    description:
      "Where ancient Silk Road history meets futuristic architecture - Explore the 'City of Winds' and the unique natural wonders of Azerbaijan.",
  },
  {
    id: "indonesia-bali",
    destination: "Indonesia (Bali)",
    countryCode: "IDN",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 45000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Uluwatu Temple Sunset",
      "Ubud Tegalalang Rice Terrace",
      "Nusa Penida Island Tour",
      "Tanah Lot Temple",
    ],
    inclusions: [
      "Private Pool Villa Experience",
      "Daily Breakfast",
      "Private Car with Driver",
      "Island Hopping Tours",
      "Spa Treatment",
    ],
    image: "bali rice terrace ubud",
    description:
      "Immerse yourself in the Island of Gods - From spiritual temples and lush rice terraces to world-class beaches and private villa luxury.",
  },
  {
    id: "malaysia-5n-6d-budget",
    destination: "Malaysia",
    countryCode: "MYS",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 45000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Petronas Twin Towers",
      "Batu Caves",
      "Genting Highlands",
      "Kuala Lumpur City Tour",
    ],
    inclusions: [
      "Premium Hotel Stay",
      "Daily Breakfast",
      "Private Transfers",
      "Expert Guided Sightseeing",
    ],
    image: "kuala lumpur skyline petronas",
    description:
      "Experience the vibrant heart of Southeast Asia - From the iconic Twin Towers to the cultural wonders of Batu Caves and the cool heights of Genting.",
  },
  {
    id: "turkey-5n-6d",
    destination: "Turkey",
    countryCode: "TUR",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 199999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Cappadocia Hot Air Balloon",
      "Bosphorus Dinner Cruise",
      "Hagia Sophia & Blue Mosque",
      "Pamukkale Thermal Pools",
    ],
    inclusions: [
      "Cave Hotel Experience in Cappadocia",
      "5-Star Hotels",
      "Hot Air Balloon Ride",
      "Domestic Flights",
      "Cultural Tours",
    ],
    image: "cappadocia balloons turkey",
    description:
      "A mesmerizing journey across continents - Experience the fairytale landscapes of Cappadocia and the historic grandeur of Istanbul.",
  },
  {
    id: "dubai-5n-6d",
    destination: "Dubai",
    countryCode: "ARE",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 69500,
    pricePerPerson: true,
    taxes: "+5% TCS",
    flightIncluded: false,
    highlights: [
      "Burj Khalifa 124th Floor",
      "Premium Desert Safari with BBQ",
      "Dubai Mall & Fountain Show",
      "Museum of the Future",
    ],
    inclusions: [
      "Luxury 4-Star Stay",
      "Daily Breakfast",
      "Adventure Desert Safari",
      "Yacht Tour",
      "Airport Transfers",
    ],
    image: "dubai skyline burj khalifa",
    description:
      "Experience the pinnacle of luxury and innovation - From the world's tallest building to thrilling desert adventures in the City of Gold.",
  },
  {
    id: "scotland-london-6n-7d",
    destination: "Scotland & London",
    countryCode: "GBR",
    duration: "6N / 7D",
    nights: 6,
    days: 7,
    priceINR: 200000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "London Eye & Big Ben",
      "Edinburgh Castle",
      "Loch Ness & Highlands",
      "Harry Potter Studio Tour",
    ],
    inclusions: [
      "Centrally Located Hotels",
      "Scottish Highlands Tour",
      "Inter-city Train Travel",
      "Guided City Walks",
      "Breakfast",
    ],
    image: "london tower bridge night",
    description:
      "The Best of Britain - Witness the royal majesty of London and the rugged, mystical beauty of the Scottish Highlands.",
  },
  {
    id: "andaman-4n-5d",
    destination: "Andaman",
    countryCode: "IND",
    duration: "4N / 5D",
    nights: 4,
    days: 5,
    priceINR: 22999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Havelock Island Scuba Diving",
      "Radhanagar Beach Sunset",
      "Cellular Jail Sound & Light Show",
      "Neil Island",
    ],
    inclusions: [
      "Premium Beach Resorts",
      "Private Ferry Transfers",
      "Snorkeling Session",
      "Daily Breakfast",
      "Sightseeing",
    ],
    image: "andaman radhanagar beach",
    description:
      "India's Tropical Gem - Discover crystal-clear turquoise waters, vibrant coral reefs, and the serene white sands of the Andaman Islands.",
  },
  {
    id: "maldives-4n-5d",
    destination: "Maldives",
    countryCode: "MDV",
    duration: "4N / 5D",
    nights: 4,
    days: 5,
    priceINR: 300000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Luxury Overwater Villa Stay",
      "Sunset Dolphin Cruise",
      "Private Island Dining",
      "Sandbank Picnic",
    ],
    inclusions: [
      "All-Inclusive Meal Plan",
      "Speedboat Transfers",
      "Snorkeling Gear",
      "Romantic Room Decoration",
      "Spa Credit",
    ],
    image: "maldives overwater villa luxury",
    description:
      "The ultimate romantic escape - Experience unparalleled luxury in your private overwater villa surrounded by endless shades of blue.",
  },
  {
    id: "china-9n-10d",
    destination: "China",
    countryCode: "CHN",
    duration: "9N / 10D",
    nights: 9,
    days: 10,
    priceINR: 199999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Great Wall of China",
      "Forbidden City Beijing",
      "Terracotta Warriors Xi'an",
      "The Bund Shanghai",
    ],
    inclusions: [
      "4-Star International Hotels",
      "Bullet Train Travel",
      "Full-time English Guide",
      "Cultural Performance Tickets",
      "All Entrance Fees",
    ],
    image: "great wall of china beijing",
    description:
      "A journey through 5,000 years of history - From the ancient Great Wall to the futuristic neon skyline of Shanghai.",
  },
  {
    id: "europe-13n-14d",
    destination: "Europe",
    countryCode: "EUR",
    duration: "13N / 14D",
    nights: 13,
    days: 14,
    priceINR: 325000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Paris Eiffel Tower",
      "Swiss Alps Jungfraujoch",
      "Venice Gondola Ride",
      "Rome Colosseum",
      "Amsterdam Canal Cruise",
    ],
    inclusions: [
      "Premium 4-Star Hotels",
      "European Rail Pass",
      "Mt Titlis Excursion",
      "City Sightseeing Tours",
      "Daily Continental Breakfast",
    ],
    image: "switzerland jungfraujoch alps",
    description:
      "The Grand European Tour - Explore the most iconic cities and breathtaking landscapes across 5 magical European countries.",
  },
  {
    id: "sri-lanka-5n-6d",
    destination: "Sri Lanka",
    countryCode: "LKA",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 40000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Sigiriya Rock Fortress",
      "Kandy Tooth Temple",
      "Ella Scenic Train Ride",
      "Bentota Beach & Water Sports",
    ],
    inclusions: [
      "Eco-friendly Luxury Resorts",
      "Private Chauffeur Guide",
      "Wildlife Safari at Udawalawe",
      "Daily Breakfast",
      "Tea Plantation Tour",
    ],
    image: "sri lanka sigiriya rock",
    description:
      "The Resplendent Isle - Experience a rich tapestry of ancient kingdoms, misty tea plantations, and golden tropical beaches.",
  },
  {
    id: "vietnam-5n-6d",
    destination: "Vietnam",
    countryCode: "VNM",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 59999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Ha Long Bay Luxury Cruise",
      "Hoi An Ancient Town",
      "Cu Chi Tunnels",
      "Hanoi Old Quarter",
    ],
    inclusions: [
      "Boutique Hotel Stays",
      "Overnight Cruise in Ha Long Bay",
      "Internal Flight",
      "Cooking Class Experience",
      "Airport Transfers",
    ],
    image: "vietnam ha long bay cruise",
    description:
      "Timeless Charm - Discover the stunning karst landscapes of Ha Long Bay and the vibrant, historic streets of Vietnam's ancient towns.",
  },
  {
    id: "cambodia-4n-5d",
    destination: "Cambodia",
    countryCode: "KHM",
    duration: "4N / 5D",
    nights: 4,
    days: 5,
    priceINR: 59999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Angkor Wat Sunrise",
      "Ta Prohm (Tomb Raider Temple)",
      "Phnom Penh Royal Palace",
      "Killing Fields",
    ],
    inclusions: [
      "Premium Hotel Stay",
      "Expert Archaeological Guide",
      "Daily Breakfast",
      "Private Airport Transfers",
      "Temple Entrance Passes",
    ],
    image: "cambodia angkor wat sunrise",
    description:
      "The Kingdom of Wonder - Witness the majestic sunrise over Angkor Wat and explore the deep-rooted history and culture of Cambodia.",
  },
  {
    id: "cambodia-5n-6d",
    destination: "Cambodia",
    countryCode: "KHM",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 75000,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Angkor Wat & Angkor Thom",
      "Tonle Sap Lake Floating Village",
      "Sihanoukville Beach",
      "Phnom Penh City Tour",
    ],
    inclusions: [
      "5-Star Luxury Resorts",
      "Private Chauffeur",
      "Sunset Boat Cruise",
      "Premium All-Inclusive Dining",
      "Spa & Wellness Session",
    ],
    image: "cambodia temple monk",
    description:
      "Extended Luxury Journey - A deep dive into Cambodia's spiritual heart and relaxing coastal escapes in total luxury.",
  },
  {
    id: "lakshadweep-4n-5d",
    destination: "Lakshadweep Island",
    countryCode: "IND",
    duration: "4N / 5D",
    nights: 4,
    days: 5,
    priceINR: 49999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Agatti Island Lagoon",
      "Bangaram Sandbank",
      "Scuba Diving & Snorkeling",
      "Glass Bottom Boat Ride",
    ],
    inclusions: [
      "Beach-front Cottages",
      "All Meals (AP Plan)",
      "Entry Permits",
      "Inter-Island Boat Transfers",
      "Water Sports Voucher",
    ],
    image: "lakshadweep islands aerial",
    description:
      "India's Secret Paradise - Escape to the pristine coral atolls and turquoise lagoons of Lakshadweep for a true island adventure.",
  },
  {
    id: "egypt-4n-5d",
    destination: "Egypt",
    countryCode: "EGY",
    duration: "4N / 5D",
    nights: 4,
    days: 5,
    priceINR: 59999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Giza Pyramids & Sphinx",
      "Egyptian Museum Cairo",
      "Khan el-Khalili Bazaar",
      "Nile River Felucca Ride",
    ],
    inclusions: [
      "Centrally Located 4-Star Stay",
      "Daily Breakfast",
      "Certified Egyptologist Guide",
      "Sound & Light Show",
      "Airport Transfers",
    ],
    image: "egypt pyramids sphinx",
    description:
      "Journey through Time - Explore the mysteries of the Pharaohs and the ancient wonders of the Nile in the heart of Egypt.",
  },
  {
    id: "japan-6n-7d",
    destination: "Japan",
    countryCode: "JPN",
    duration: "6N / 7D",
    nights: 6,
    days: 7,
    priceINR: 149999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: ["Tokyo", "Kyoto", "Osaka", "Mt Fuji"],
    inclusions: ["4-Star Hotel", "Breakfast", "Bullet Train Pass", "City Tours"],
    image: "japan tokyo city",
    description: "Land of the Rising Sun - Futuristic cities, ancient temples and cherry blossoms",
  },
  {
    id: "switzerland-5n-6d",
    destination: "Switzerland",
    countryCode: "CHE",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 189999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: ["Zurich", "Lucerne", "Interlaken", "Mt Titlis"],
    inclusions: ["4-Star Hotel", "Breakfast", "Swiss Rail Pass", "Mountain Excursions"],
    image: "switzerland alps",
    description: "Heaven on Earth - Snow-capped peaks, crystal lakes and chocolate box villages",
  },
  {
    id: "mauritius-5n-6d",
    destination: "Mauritius",
    countryCode: "MUS",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 89999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: ["North Island", "South Island", "Ile Aux Cerfs", "Chamarel"],
    inclusions: ["Beach Resort", "Breakfast & Dinner", "Island Tours", "Transfers"],
    image: "mauritius beach",
    description: "Tropical Paradise - Turquoise lagoons, coral reefs and white sandy beaches",
  },
  {
    id: "seychelles-4n-5d",
    destination: "Seychelles",
    countryCode: "SYC",
    duration: "4N / 5D",
    nights: 4,
    days: 5,
    priceINR: 129999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: ["Mahe Island", "Praslin", "La Digue", "Vallee de Mai"],
    inclusions: ["Luxury Resort", "Breakfast", "Island Hopping", "Airport Transfers"],
    image: "seychelles beach",
    description: "Island Paradise - Pristine beaches, giant tortoises and rare flora",
  },
  {
    id: "australia-8n-9d",
    destination: "Australia",
    countryCode: "AUS",
    duration: "8N / 9D",
    nights: 8,
    days: 9,
    priceINR: 249999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: ["Sydney Opera House", "Melbourne", "Great Barrier Reef", "Gold Coast"],
    inclusions: ["4-Star Hotel", "Breakfast", "Domestic Flights", "Sightseeing"],
    image: "sydney opera house",
    description: "Land Down Under - Vibrant cities, stunning coastlines and unique wildlife",
  },
  {
    id: "south-korea-5n-6d",
    destination: "South Korea",
    countryCode: "KOR",
    duration: "5N / 6D",
    nights: 5,
    days: 6,
    priceINR: 119999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: ["Seoul Tower", "Gyeongbokgung Palace", "DMZ Tour", "Jeju Island"],
    inclusions: [
      "Luxury City Hotel",
      "Daily Breakfast",
      "Bullet Train Experience",
      "Traditional K-Food Tour",
      "Guided City Sightseeing",
    ],
    image: "seoul south korea skyline night",
    description:
      "Where Tradition meets K-Pop - Experience the perfect harmony of ancient palaces and ultra-modern lifestyle.",
  },
  {
    id: "usa-9n-10d",
    destination: "USA",
    countryCode: "USA",
    duration: "9N / 10D",
    nights: 9,
    days: 10,
    priceINR: 349999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "New York Times Square",
      "Statue of Liberty",
      "Las Vegas Strip",
      "Grand Canyon",
      "Hollywood",
    ],
    inclusions: [
      "Premium 4-Star Hotels",
      "Internal Flights",
      "Guided Canyon Tour",
      "City Sightseeing Pass",
      "Private Transfers",
    ],
    image: "new york city skyline manhattan",
    description:
      "The American Dream - A grand coast-to-coast journey from the neon lights of NYC to the natural wonders of the Grand Canyon.",
  },
  {
    id: "canada-7n-8d",
    destination: "Canada",
    countryCode: "CAN",
    duration: "7N / 8D",
    nights: 7,
    days: 8,
    priceINR: 289999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: ["Niagara Falls", "Toronto CN Tower", "Banff National Park", "Rocky Mountains"],
    inclusions: [
      "Mountain Resort Stay",
      "Niagara Falls Boat Tour",
      "Rocky Mountaineer Train Experience",
      "Daily Gourmet Breakfast",
      "National Park Fees",
    ],
    image: "banff national park canada mountains",
    description:
      "The Great White North - Experience breathtaking alpine beauty, majestic waterfalls, and vibrant cosmopolitan cities.",
  },
  {
    id: "new-zealand-8n-9d",
    destination: "New Zealand",
    countryCode: "NZL",
    duration: "8N / 9D",
    nights: 8,
    days: 9,
    priceINR: 319999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Milford Sound Cruise",
      "Hobbiton Movie Set",
      "Queenstown Adventure",
      "Waitomo Glowworm Caves",
    ],
    inclusions: [
      "Boutique Lodge Stays",
      "Private Fjord Cruise",
      "Lord of the Rings Tour",
      "Adventure Activity Voucher",
      "Luxury Rental Car/Transfer",
    ],
    image: "milford sound new zealand landscape",
    description:
      "The Adventure Capital - A magical journey through Middle-earth landscapes, dramatic fjords, and thrilling outdoor escapes.",
  },
  {
    id: "south-africa-7n-8d",
    destination: "South Africa",
    countryCode: "ZAF",
    duration: "7N / 8D",
    nights: 7,
    days: 8,
    priceINR: 179999,
    pricePerPerson: true,
    taxes: "",
    flightIncluded: false,
    highlights: [
      "Kruger National Park Safari",
      "Table Mountain",
      "Cape Town Waterfront",
      "Garden Route Drive",
    ],
    inclusions: [
      "Luxury Safari Lodge",
      "4x4 Big Five Game Drives",
      "Cape Town City Tour",
      "Vineyard Experience",
      "All Internal Transfers",
    ],
    image: "cape town south africa table mountain",
    description:
      "A World in One Country - Encounter the Big Five on safari and witness the stunning coastal beauty of Cape Town.",
  },
];

// Helper function to get package by ID
export function getPackageById(id: string): InternationalPackage | undefined {
  return INTERNATIONAL_PACKAGES.find((pkg) => pkg.id === id);
}

// Helper function to get packages by destination
export function getPackagesByDestination(destination: string): InternationalPackage[] {
  return INTERNATIONAL_PACKAGES.filter(
    (pkg) => pkg.destination.toLowerCase() === destination.toLowerCase(),
  );
}

// Helper function to format price display
export function formatPriceDisplay(package_: InternationalPackage): string {
  const perPersonText = package_.pricePerPerson ? " per person" : "";
  const taxesText = package_.taxes ? ` + ${package_.taxes}` : "";
  return `₹${package_.priceINR.toLocaleString("en-IN")}${perPersonText}${taxesText}`;
}

// Get all unique destinations
export function getUniqueDestinations(): string[] {
  const destinations = new Set(INTERNATIONAL_PACKAGES.map((pkg) => pkg.destination));
  return Array.from(destinations);
}
