/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PackageIndividualRouteImport } from './routes/package-individual'
import { Route as PackageGroupRouteImport } from './routes/package-group'
import { Route as PackageFamilyRouteImport } from './routes/package-family'
import { Route as PackageBikeRouteImport } from './routes/package-bike'
import { Route as PackageBackpackRouteImport } from './routes/package-backpack'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MobileViewIndexRouteImport } from './routes/mobile-view/index'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as MobileViewVisaRouteImport } from './routes/mobile-view/visa'
import { Route as MobileViewServicesRouteImport } from './routes/mobile-view/services'
import { Route as MobileViewPassportRouteImport } from './routes/mobile-view/passport'
import { Route as MobileViewPackagesRouteImport } from './routes/mobile-view/packages'
import { Route as MobileViewInternationalRouteImport } from './routes/mobile-view/international'
import { Route as MobileViewContactRouteImport } from './routes/mobile-view/contact'
import { Route as MobileViewCartRouteImport } from './routes/mobile-view/cart'
import { Route as MobileViewAboutRouteImport } from './routes/mobile-view/about'
import { Route as CountriesCodeRouteImport } from './routes/countries.$code'
import { Route as MobileViewCountriesIndexRouteImport } from './routes/mobile-view/countries.index'
import { Route as MobileViewCountriesCodeRouteImport } from './routes/mobile-view/countries.$code'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIndividualRoute = PackageIndividualRouteImport.update({
  id: '/package-individual',
  path: '/package-individual',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageGroupRoute = PackageGroupRouteImport.update({
  id: '/package-group',
  path: '/package-group',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageFamilyRoute = PackageFamilyRouteImport.update({
  id: '/package-family',
  path: '/package-family',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageBikeRoute = PackageBikeRouteImport.update({
  id: '/package-bike',
  path: '/package-bike',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageBackpackRoute = PackageBackpackRouteImport.update({
  id: '/package-backpack',
  path: '/package-backpack',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewIndexRoute = MobileViewIndexRouteImport.update({
  id: '/mobile-view/',
  path: '/mobile-view/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewVisaRoute = MobileViewVisaRouteImport.update({
  id: '/mobile-view/visa',
  path: '/mobile-view/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewServicesRoute = MobileViewServicesRouteImport.update({
  id: '/mobile-view/services',
  path: '/mobile-view/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewPassportRoute = MobileViewPassportRouteImport.update({
  id: '/mobile-view/passport',
  path: '/mobile-view/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewPackagesRoute = MobileViewPackagesRouteImport.update({
  id: '/mobile-view/packages',
  path: '/mobile-view/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewInternationalRoute = MobileViewInternationalRouteImport.update({
  id: '/mobile-view/international',
  path: '/mobile-view/international',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewContactRoute = MobileViewContactRouteImport.update({
  id: '/mobile-view/contact',
  path: '/mobile-view/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewCartRoute = MobileViewCartRouteImport.update({
  id: '/mobile-view/cart',
  path: '/mobile-view/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewAboutRoute = MobileViewAboutRouteImport.update({
  id: '/mobile-view/about',
  path: '/mobile-view/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCodeRoute = CountriesCodeRouteImport.update({
  id: '/countries/$code',
  path: '/countries/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileViewCountriesIndexRoute =
  MobileViewCountriesIndexRouteImport.update({
    id: '/mobile-view/countries/',
    path: '/mobile-view/countries/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MobileViewCountriesCodeRoute = MobileViewCountriesCodeRouteImport.update({
  id: '/mobile-view/countries/$code',
  path: '/mobile-view/countries/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/package-backpack': typeof PackageBackpackRoute
  '/package-bike': typeof PackageBikeRoute
  '/package-family': typeof PackageFamilyRoute
  '/package-group': typeof PackageGroupRoute
  '/package-individual': typeof PackageIndividualRoute
  '/packages': typeof PackagesRoute
  '/passport': typeof PassportRoute
  '/services': typeof ServicesRoute
  '/visa': typeof VisaRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/mobile-view/about': typeof MobileViewAboutRoute
  '/mobile-view/cart': typeof MobileViewCartRoute
  '/mobile-view/contact': typeof MobileViewContactRoute
  '/mobile-view/international': typeof MobileViewInternationalRoute
  '/mobile-view/packages': typeof MobileViewPackagesRoute
  '/mobile-view/passport': typeof MobileViewPassportRoute
  '/mobile-view/services': typeof MobileViewServicesRoute
  '/mobile-view/visa': typeof MobileViewVisaRoute
  '/countries/': typeof CountriesIndexRoute
  '/mobile-view/': typeof MobileViewIndexRoute
  '/mobile-view/countries/$code': typeof MobileViewCountriesCodeRoute
  '/mobile-view/countries/': typeof MobileViewCountriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/package-backpack': typeof PackageBackpackRoute
  '/package-bike': typeof PackageBikeRoute
  '/package-family': typeof PackageFamilyRoute
  '/package-group': typeof PackageGroupRoute
  '/package-individual': typeof PackageIndividualRoute
  '/packages': typeof PackagesRoute
  '/passport': typeof PassportRoute
  '/services': typeof ServicesRoute
  '/visa': typeof VisaRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/mobile-view/about': typeof MobileViewAboutRoute
  '/mobile-view/cart': typeof MobileViewCartRoute
  '/mobile-view/contact': typeof MobileViewContactRoute
  '/mobile-view/international': typeof MobileViewInternationalRoute
  '/mobile-view/packages': typeof MobileViewPackagesRoute
  '/mobile-view/passport': typeof MobileViewPassportRoute
  '/mobile-view/services': typeof MobileViewServicesRoute
  '/mobile-view/visa': typeof MobileViewVisaRoute
  '/countries': typeof CountriesIndexRoute
  '/mobile-view': typeof MobileViewIndexRoute
  '/mobile-view/countries/$code': typeof MobileViewCountriesCodeRoute
  '/mobile-view/countries': typeof MobileViewCountriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/package-backpack': typeof PackageBackpackRoute
  '/package-bike': typeof PackageBikeRoute
  '/package-family': typeof PackageFamilyRoute
  '/package-group': typeof PackageGroupRoute
  '/package-individual': typeof PackageIndividualRoute
  '/packages': typeof PackagesRoute
  '/passport': typeof PassportRoute
  '/services': typeof ServicesRoute
  '/visa': typeof VisaRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/mobile-view/about': typeof MobileViewAboutRoute
  '/mobile-view/cart': typeof MobileViewCartRoute
  '/mobile-view/contact': typeof MobileViewContactRoute
  '/mobile-view/international': typeof MobileViewInternationalRoute
  '/mobile-view/packages': typeof MobileViewPackagesRoute
  '/mobile-view/passport': typeof MobileViewPassportRoute
  '/mobile-view/services': typeof MobileViewServicesRoute
  '/mobile-view/visa': typeof MobileViewVisaRoute
  '/countries/': typeof CountriesIndexRoute
  '/mobile-view/': typeof MobileViewIndexRoute
  '/mobile-view/countries/$code': typeof MobileViewCountriesCodeRoute
  '/mobile-view/countries/': typeof MobileViewCountriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/package-backpack'
    | '/package-bike'
    | '/package-family'
    | '/package-group'
    | '/package-individual'
    | '/packages'
    | '/passport'
    | '/services'
    | '/visa'
    | '/countries/$code'
    | '/mobile-view/about'
    | '/mobile-view/cart'
    | '/mobile-view/contact'
    | '/mobile-view/international'
    | '/mobile-view/packages'
    | '/mobile-view/passport'
    | '/mobile-view/services'
    | '/mobile-view/visa'
    | '/countries/'
    | '/mobile-view/'
    | '/mobile-view/countries/$code'
    | '/mobile-view/countries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/package-backpack'
    | '/package-bike'
    | '/package-family'
    | '/package-group'
    | '/package-individual'
    | '/packages'
    | '/passport'
    | '/services'
    | '/visa'
    | '/countries/$code'
    | '/mobile-view/about'
    | '/mobile-view/cart'
    | '/mobile-view/contact'
    | '/mobile-view/international'
    | '/mobile-view/packages'
    | '/mobile-view/passport'
    | '/mobile-view/services'
    | '/mobile-view/visa'
    | '/countries'
    | '/mobile-view'
    | '/mobile-view/countries/$code'
    | '/mobile-view/countries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/package-backpack'
    | '/package-bike'
    | '/package-family'
    | '/package-group'
    | '/package-individual'
    | '/packages'
    | '/passport'
    | '/services'
    | '/visa'
    | '/countries/$code'
    | '/mobile-view/about'
    | '/mobile-view/cart'
    | '/mobile-view/contact'
    | '/mobile-view/international'
    | '/mobile-view/packages'
    | '/mobile-view/passport'
    | '/mobile-view/services'
    | '/mobile-view/visa'
    | '/countries/'
    | '/mobile-view/'
    | '/mobile-view/countries/$code'
    | '/mobile-view/countries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  PackageBackpackRoute: typeof PackageBackpackRoute
  PackageBikeRoute: typeof PackageBikeRoute
  PackageFamilyRoute: typeof PackageFamilyRoute
  PackageGroupRoute: typeof PackageGroupRoute
  PackageIndividualRoute: typeof PackageIndividualRoute
  PackagesRoute: typeof PackagesRoute
  PassportRoute: typeof PassportRoute
  ServicesRoute: typeof ServicesRoute
  VisaRoute: typeof VisaRoute
  CountriesCodeRoute: typeof CountriesCodeRoute
  MobileViewAboutRoute: typeof MobileViewAboutRoute
  MobileViewCartRoute: typeof MobileViewCartRoute
  MobileViewContactRoute: typeof MobileViewContactRoute
  MobileViewInternationalRoute: typeof MobileViewInternationalRoute
  MobileViewPackagesRoute: typeof MobileViewPackagesRoute
  MobileViewPassportRoute: typeof MobileViewPassportRoute
  MobileViewServicesRoute: typeof MobileViewServicesRoute
  MobileViewVisaRoute: typeof MobileViewVisaRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  MobileViewIndexRoute: typeof MobileViewIndexRoute
  MobileViewCountriesCodeRoute: typeof MobileViewCountriesCodeRoute
  MobileViewCountriesIndexRoute: typeof MobileViewCountriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-individual': {
      id: '/package-individual'
      path: '/package-individual'
      fullPath: '/package-individual'
      preLoaderRoute: typeof PackageIndividualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-group': {
      id: '/package-group'
      path: '/package-group'
      fullPath: '/package-group'
      preLoaderRoute: typeof PackageGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-family': {
      id: '/package-family'
      path: '/package-family'
      fullPath: '/package-family'
      preLoaderRoute: typeof PackageFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-bike': {
      id: '/package-bike'
      path: '/package-bike'
      fullPath: '/package-bike'
      preLoaderRoute: typeof PackageBikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package-backpack': {
      id: '/package-backpack'
      path: '/package-backpack'
      fullPath: '/package-backpack'
      preLoaderRoute: typeof PackageBackpackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/': {
      id: '/mobile-view/'
      path: '/mobile-view'
      fullPath: '/mobile-view/'
      preLoaderRoute: typeof MobileViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/visa': {
      id: '/mobile-view/visa'
      path: '/mobile-view/visa'
      fullPath: '/mobile-view/visa'
      preLoaderRoute: typeof MobileViewVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/services': {
      id: '/mobile-view/services'
      path: '/mobile-view/services'
      fullPath: '/mobile-view/services'
      preLoaderRoute: typeof MobileViewServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/passport': {
      id: '/mobile-view/passport'
      path: '/mobile-view/passport'
      fullPath: '/mobile-view/passport'
      preLoaderRoute: typeof MobileViewPassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/packages': {
      id: '/mobile-view/packages'
      path: '/mobile-view/packages'
      fullPath: '/mobile-view/packages'
      preLoaderRoute: typeof MobileViewPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/international': {
      id: '/mobile-view/international'
      path: '/mobile-view/international'
      fullPath: '/mobile-view/international'
      preLoaderRoute: typeof MobileViewInternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/contact': {
      id: '/mobile-view/contact'
      path: '/mobile-view/contact'
      fullPath: '/mobile-view/contact'
      preLoaderRoute: typeof MobileViewContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/cart': {
      id: '/mobile-view/cart'
      path: '/mobile-view/cart'
      fullPath: '/mobile-view/cart'
      preLoaderRoute: typeof MobileViewCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/about': {
      id: '/mobile-view/about'
      path: '/mobile-view/about'
      fullPath: '/mobile-view/about'
      preLoaderRoute: typeof MobileViewAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$code': {
      id: '/countries/$code'
      path: '/countries/$code'
      fullPath: '/countries/$code'
      preLoaderRoute: typeof CountriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/countries/': {
      id: '/mobile-view/countries/'
      path: '/mobile-view/countries'
      fullPath: '/mobile-view/countries/'
      preLoaderRoute: typeof MobileViewCountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-view/countries/$code': {
      id: '/mobile-view/countries/$code'
      path: '/mobile-view/countries/$code'
      fullPath: '/mobile-view/countries/$code'
      preLoaderRoute: typeof MobileViewCountriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  PackageBackpackRoute: PackageBackpackRoute,
  PackageBikeRoute: PackageBikeRoute,
  PackageFamilyRoute: PackageFamilyRoute,
  PackageGroupRoute: PackageGroupRoute,
  PackageIndividualRoute: PackageIndividualRoute,
  PackagesRoute: PackagesRoute,
  PassportRoute: PassportRoute,
  ServicesRoute: ServicesRoute,
  VisaRoute: VisaRoute,
  CountriesCodeRoute: CountriesCodeRoute,
  MobileViewAboutRoute: MobileViewAboutRoute,
  MobileViewCartRoute: MobileViewCartRoute,
  MobileViewContactRoute: MobileViewContactRoute,
  MobileViewInternationalRoute: MobileViewInternationalRoute,
  MobileViewPackagesRoute: MobileViewPackagesRoute,
  MobileViewPassportRoute: MobileViewPassportRoute,
  MobileViewServicesRoute: MobileViewServicesRoute,
  MobileViewVisaRoute: MobileViewVisaRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  MobileViewIndexRoute: MobileViewIndexRoute,
  MobileViewCountriesCodeRoute: MobileViewCountriesCodeRoute,
  MobileViewCountriesIndexRoute: MobileViewCountriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
